# Generated by Django 3.2.5 on 2021-07-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('by', models.CharField(blank=True, max_length=255)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('kids', models.JSONField(blank=True, null=True)),
                ('parts', models.JSONField(blank=True, null=True)),
                ('descendants', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
                ('custom', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
